## Travis configuration file for gpuClassifieR

language: r

warnings_are_errors: false
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

r_packages:
 - devtools
 - testthat

r_github_packages:
 - hadley/devtools

after_failure:
 - sudo cat /home/travis/build/IshmaelBelghazi/gpuClassifieR/gpuClassifieR.Rcheck/00install.out

notifications:
 email:
  on_success: always
  on_failure: always
